### ISSUE TITLE
`Bitmap` is unsound

### ISSUE THREAD

**Issue by MaxVerevkin** [katyo/msdfgen-rs#18]
- The memory is not initialized, but `Bitmap` provides safe functions to access the memory and the `Drop` implementation drops each element.
- `Vec::with_capacity` is allowed to allocate more memory than requested. The `Drop` implementation does not account for that.

This unsafe-free code segfaults:

```rust
fn main() {
    let _bm = msdfgen::Bitmap::<Vec<u8>>::new(2, 2);
}
```

---

Consider adding `T: bytemuck::Pod` restriction for `Bitmap`, zeroing the memory in the constructor and using `Vec::reserve_exact`.

**Comment by katyo** [comment]
@MaxVerevkin Could you fix this? PRs are welcome!
