### ISSUE TITLE
Latest Mac x86_64 and other CI builds failing

### ISSUE THREAD

**Issue by marceline-cramer** [katyo/msdfgen-rs#21]
Hey, recently `msdfgen-sys` started failing to build on Mac in [my own project](https://github.com/hearth-rs/hearth), and when I [forked msdfgen-rs and tried running the full CI suite](https://github.com/hearth-rs/msdfgen-rs/pull/1) to dig deeper, I noticed that LOTS of CI is failing, specifically Mac and the MIPS targets.

The root cause of the Mac failure seems to be:
```
cargo:warning=clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
```

Meanwhile, the MIPS builds seem to be failing because the MIPS Rust toolchains aren't available. Maybe they got renamed or removed from rustup?

I'm opening an issue here so that the upstream is informed but since these CI failures are blocking my project, I'm also going to be trying to fix this on my fork independently and immediately.

**Comment by marceline-cramer** [comment]
Managed to get Mac builds to at least compile by adding this to `build_library` in `sys/build.rs`:

```rs
    let target = std::env::var("TARGET").expect("TARGET is set by cargo.");

    if target.contains("-darwin") {
        build.cpp_set_stdlib("c++");
    }
```

I have zero clue if this is the best way to do this since I am by no means a devops expert, but this at least gets Mac to build and pass CI.

**Comment by marceline-cramer** [comment]
Hey @katyo, I've been trying to reach you regarding this issue but it seems like your email server is unavailable.

**Comment by marceline-cramer** [comment]
@katyo

**Comment by katyo** [comment]
@marceline-cramer Could you create pull request with fix? If mips support was removed from Rust toolchain, feel free to remove it from CI too.

**Comment by marceline-cramer** [comment]
Definitely! I've opened #22 with both the Mac OS and MIPS CI fixes. :)
